-- Type: account_type

-- DROP TYPE IF EXISTS public.account_type;

CREATE TYPE public.account_type AS ENUM
    ('Client ', 'Employee ', 'Admin ');

ALTER TYPE public.account_type
    OWNER TO gage;

--Table structure for table 'classification'
create table public.classification(
    classification_id int generated by default as identity,
    classification_name character varying not null,
    constraint classification_pk primary key (classification_id)
)

    CREATE TABLE IF NOT EXISTS Public.inventory(
	INV_ID INTEGER NOT NULL generated by default as identity,
	inv_make character varying not null,
	inv_model character varying not null,
	inv_year character(4) not null,
	inv_description text not null,
	inv_image character varying not null,
	inv_thumbnail character varying not null,
	inv_price numeric (9, 0) NOT NULL, 
	inv_miles integer not null,
	inv_color character varying not null,
	classification_id integer not null,
	constraint inventory_pkey Primary Key (inv_id)
);

alter table if exists public.inventory
	add constraint fk_classification foreign key (classification_id)
	references public.classification (classification_id) match simple
	on update cascade
	on delete no action;

-- data for table 'classification'
insert into public.classification (classification_name)
values('Custom'),
	('Sport'),
	('SUV'),
	('Truck'),
	('Sedan');